### ISSUE TITLE
Catch inline actions

### ISSUE THREAD

**Issue by kesar** [EOSIO/demux-js#19]
Right now if an action is inside another actions this system wont catch it, data stored could be incomplete

**Comment by flux627** [comment]
Hi kesar! Thanks for the issue report. We're aware of the issue and we're currently working on solving it by utilizing the MongoDB plugin for Nodeos and creating a corresponding MongoActionReader. Since the MongoDB plugin stores inline action information, we will be able to include these actions. in the normalized Block output.

We currently have no ETA for this feature, but it is high on our priority list.

Here's the branch for you to follow:
https://github.com/EOSIO/demux-js/tree/mongodb

**Comment by flux627** [comment]
Closing, feel free to reopen on EOSIO/demux-js-eos where it now belongs.
