### ISSUE TITLE
block handler

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [EOSIO/demux-js#24]
Hi.

Are you going to make block handler any time soon to watch for whole blocks?

**Comment by Vasiliy-Bondarenko** [comment]
Can i just extend AbstractActionHandler like this:
```js
class ObjectActionHandler extends AbstractActionHandler {

    async handleBlock(block, isRollback, isFirstBlock, isReplay){

      // do something with the block
      console.log(block);

      return super.handleBlock(block, isRollback, isFirstBlock, isReplay)
    }
```

and another question - how to prevent block getting blocks from forks? is there a way to just delay processing to let's say 100 blocks? 

or i must somehow track blocks and replace blocks by block_num with newer one? is it the correct way to go?

will i get all blocks in case of switching forks?

**Comment by jeffreyssmith2nd** [comment]
Is there something you need from the whole block vs the actions?

As for preventing blocks that are on forks, you can set `onlyIrreversible=true` when you initialize the ActionHandler.

In the case of a fork where `onlyIrreversible=false`, `rollback` will be called and then it start processing the blocks that were not on the fork.

**Comment by Vasiliy-Bondarenko** [comment]
Yes, i need the creator of the block. I'm calculating performance stats for BPs: http://eosbpstats.com/
Now i'm doing it with mongodb plugin, but would like to switch to demux to have the dataset in more useful shape for me.

**Comment by chris-allnutt** [comment]
@Vasiliy-Bondarenko I believe this would just need to be added to the block type in : https://github.com/EOSIO/demux-js/blob/develop/index.d.ts#L7

and added here as well for deserialization: 
https://github.com/EOSIO/demux-js/blob/develop/src/demux/readers/eos/NodeosBlock.ts

If you don't update the nodeosblock then you won't get the data you need in the object that's passed to action handler.

If you can put up a PR for those changes, with updated test for NodeosBlock.test.ts we'd be happy to merge it in.

**Comment by flux627** [comment]
If you want to keep Demux "pure", you could create your own action reader that creates a synthetic action (perhaps called `createblock`) that contains the information you need, and prepend it to the actions array. Other than that, we should have some kind of conversation about how to extend the available information in `blockInfo`.

**Comment by flux627** [comment]
Additionally, Demux does not replace the MongoDB plugin. The MongoDB is more of an alternative to the RPC endpoint than it is an alternative for indexing data. We actually have a PR for reading from the MongoDB plugin instead of an RPC endpoint (#26) but it is still highly experimental.

**Comment by Vasiliy-Bondarenko** [comment]
@chris-allnutt, ok. i made a PR. take a look.
includes a test assertion.
did i make it right or am i missing something?

**Comment by Vasiliy-Bondarenko** [comment]
@flux627 keeping mongodb plugin always running has some downsides - it take A LOT of time (i'm talking days! even on powerful server with SSD) to replay the node when it crashes and damages the state. 
i hope demux will decouple keeping the node state and my external database with data. so i can replay the blockchain quite fast in case something happens.

**Comment by flux627** [comment]
I appreciate all your work on this Vasiliy. I have done some thinking about this and would like to share some thoughts on the best way of getting the functionality that you need, without breaking the scope or paradigm of the Demux pattern.

To address your PR: instead of having a `NodeosActionReader`, we can have a `NodeosTransactionReader`, where the passed array of `action`s have full transactions as their payloads. The `actionType` could be just `transaction`, or maybe the name of the account that initiated the transaction.

Another way (which may fit your use-case better) would be to create a `NodeosBlockReader`, where the passed `action`s have full blocks as their payloads. The `actionType` could be `createblock` or the producer account that created the block.

The main takeaway here is that Demux can do what you need without extending the scope of Demux itself, if you package your actionable events into `action`s. Demux is about processing discrete actionable events that each correspond to a mutation of state. For many use-cases, these will be literal actions that come from transactions, but for something like what you're doing (block producer stats), your "discrete actionable events" are actually full blocks. Your `action`s array should correspond with that reality.

**Comment by flux627** [comment]
@Vasiliy-Bondarenko In accordance with our recent decision to move out all class implementations into their own repositories, this no longer belongs here. I encourage you to open source any solution you came up with, however, and create another PR to include your project in the Class Implementations section of this repo's readme.
